name: Enhancement and Feature Request
description: Request a new feature, an enhancement to improve GhostBSD
#title: ""
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ### Please read this first
        Before requesting a new feature or enhancement, please ensure it is not in our [Development Management](https://github.com/orgs/ghostbsd/projects/4/views/12).

        Follow these tips to help us understand your request.
        * Only one feature or enhancement per request
        * The title describes the request
        * Follow the information of each field
        * Be concise and clear on each field
        * Make sure your request is understandable after reading it

        **Note:** If we have a problem understanding the request, we might close the request.
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature or enhancement.
      description: A clear and concise description of the feature or enhancement.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why this request?
      Description: Why is this feature or enhancement requested?
    validations:
      required: true
